use momo_compositor::{Key, ShortcutTrigger};
use thiserror::Error;

#[cfg(test)]
mod tests;

pub(super) fn wayfire_binding(trigger: &ShortcutTrigger) -> Result<String, WayfireBindingError> {
    if trigger.keys.is_empty() {
        return Err(WayfireBindingError::Empty);
    }
    let mut binding = String::new();
    for key in &trigger.keys {
        push_binding_token(&mut binding, wayfire_key_name(*key)?);
    }
    Ok(binding)
}

fn push_binding_token(binding: &mut String, token: &str) {
    if !binding.is_empty() {
        binding.push(' ');
    }
    binding.push_str(token);
}

fn wayfire_key_name(key: Key) -> Result<&'static str, WayfireBindingError> {
    let name = match key {
        Key::Control | Key::ControlLeft | Key::ControlRight => "<ctrl>",
        Key::Alt | Key::AltGraph | Key::AltLeft | Key::AltRight => "<alt>",
        Key::Shift | Key::ShiftLeft | Key::ShiftRight => "<shift>",
        Key::Meta | Key::Super | Key::SuperLeft | Key::SuperRight => "<super>",
        Key::ArrowDown => "KEY_DOWN",
        Key::ArrowLeft => "KEY_LEFT",
        Key::ArrowRight => "KEY_RIGHT",
        Key::ArrowUp => "KEY_UP",
        Key::Escape => "KEY_ESC",
        Key::Tab => "KEY_TAB",
        Key::Backspace => "KEY_BACKSPACE",
        Key::Enter => "KEY_ENTER",
        Key::Space => "KEY_SPACE",
        Key::Insert => "KEY_INSERT",
        Key::Delete => "KEY_DELETE",
        Key::Home => "KEY_HOME",
        Key::End => "KEY_END",
        Key::PageUp => "KEY_PAGEUP",
        Key::PageDown => "KEY_PAGEDOWN",
        Key::BrowserBack | Key::GoBack => "KEY_BACK",
        Key::BrowserForward => "KEY_FORWARD",
        Key::BrowserHome | Key::GoHome => "KEY_HOMEPAGE",
        Key::BrowserRefresh => "KEY_REFRESH",
        Key::BrowserSearch => "KEY_SEARCH",
        Key::BrowserStop => "KEY_STOP",
        Key::Copy => "KEY_COPY",
        Key::Cut => "KEY_CUT",
        Key::Paste => "KEY_PASTE",
        Key::Again => "KEY_AGAIN",
        Key::Find => "KEY_FIND",
        Key::Open => "KEY_OPEN",
        Key::Props => "KEY_PROPS",
        Key::Select => "KEY_SELECT",
        Key::Undo => "KEY_UNDO",
        Key::Redo => "KEY_REDO",
        Key::Accept => "KEY_OK",
        Key::Cancel => "KEY_CANCEL",
        Key::Help => "KEY_HELP",
        Key::CapsLock => "KEY_CAPSLOCK",
        Key::ContextMenu | Key::TVContentsMenu | Key::TVMediaContext => "KEY_CONTEXT_MENU",
        Key::NumLock => "KEY_NUMLOCK",
        Key::ScrollLock => "KEY_SCROLLLOCK",
        Key::PrintScreen => "KEY_SYSRQ",
        Key::Pause => "KEY_PAUSE",
        Key::Clear => "KEY_CLEAR",
        Key::NumPad0 => "KEY_KP0",
        Key::NumPad1 => "KEY_KP1",
        Key::NumPad2 => "KEY_KP2",
        Key::NumPad3 => "KEY_KP3",
        Key::NumPad4 => "KEY_KP4",
        Key::NumPad5 => "KEY_KP5",
        Key::NumPad6 => "KEY_KP6",
        Key::NumPad7 => "KEY_KP7",
        Key::NumPad8 => "KEY_KP8",
        Key::NumPad9 => "KEY_KP9",
        Key::NumPadAdd => "KEY_KPPLUS",
        Key::NumPadDecimal | Key::NumpadDecimal => "KEY_KPDOT",
        Key::NumPadDivide | Key::NumpadDivide => "KEY_KPSLASH",
        Key::NumPadEnter | Key::NumpadEnter => "KEY_KPENTER",
        Key::NumPadEqual | Key::NumpadEqual => "KEY_KPEQUAL",
        Key::NumPadMultiply | Key::NumpadMultiply | Key::NumpadStar => "KEY_KPASTERISK",
        Key::NumPadSubtract | Key::NumpadSubtract => "KEY_KPMINUS",
        Key::NumPadBackspace => "KEY_BACKSPACE",
        Key::NumPadClear | Key::NumPadClearEntry => "KEY_CLEAR",
        Key::NumpadComma => "KEY_KPCOMMA",
        Key::NumpadHash => "KEY_NUMERIC_POUND",
        Key::NumpadParenLeft => "KEY_KPLEFTPAREN",
        Key::NumpadParenRight => "KEY_KPRIGHTPAREN",
        Key::MediaPlayPause => "KEY_PLAYPAUSE",
        Key::MediaSelect | Key::LaunchMediaPlayer => "KEY_MEDIA",
        Key::MediaStop => "KEY_STOPCD",
        Key::MediaTrackNext => "KEY_NEXTSONG",
        Key::MediaTrackPrevious => "KEY_PREVIOUSSONG",
        Key::MediaClose => "KEY_CLOSECD",
        Key::MediaFastForward => "KEY_FASTFORWARD",
        Key::MediaPause => "KEY_PAUSECD",
        Key::MediaPlay | Key::Play => "KEY_PLAY",
        Key::MediaRecord => "KEY_RECORD",
        Key::MediaRewind => "KEY_REWIND",
        Key::MediaSkipBackward => "KEY_PREVIOUS",
        Key::MediaSkipForward => "KEY_NEXT",
        Key::MediaStepBackward => "KEY_FRAMEBACK",
        Key::MediaStepForward => "KEY_FRAMEFORWARD",
        Key::MediaTopMenu => "KEY_MEDIA_TOP_MENU",
        Key::RandomToggle => "KEY_SHUFFLE",
        Key::Power | Key::TVPower => "KEY_POWER",
        Key::PowerOff => "KEY_POWER2",
        Key::Sleep | Key::Standby => "KEY_SLEEP",
        Key::Suspend | Key::Hibernate => "KEY_SUSPEND",
        Key::WakeUp => "KEY_WAKEUP",
        Key::AudioVolumeDown => "KEY_VOLUMEDOWN",
        Key::AudioVolumeMute => "KEY_MUTE",
        Key::AudioVolumeUp => "KEY_VOLUMEUP",
        Key::MicrophoneVolumeMute | Key::MicrophoneToggle => "KEY_MICMUTE",
        Key::BrightnessDown => "KEY_BRIGHTNESSDOWN",
        Key::BrightnessUp => "KEY_BRIGHTNESSUP",
        Key::Eject => "KEY_EJECTCD",
        Key::LogOff => "KEY_LOGOFF",
        Key::ZoomIn => "KEY_ZOOMIN",
        Key::ZoomOut => "KEY_ZOOMOUT",
        Key::ZoomToggle => "KEY_ZOOM",
        Key::Hiragana => "KEY_HIRAGANA",
        Key::Compose => "KEY_COMPOSE",
        Key::Convert => "KEY_HENKAN",
        Key::NonConvert => "KEY_MUHENKAN",
        Key::HangulMode => "KEY_HANGEUL",
        Key::HanjaMode => "KEY_HANJA",
        Key::HiraganaKatakana => "KEY_KATAKANAHIRAGANA",
        Key::KanaMode | Key::Katakana => "KEY_KATAKANA",
        Key::ZenkakuHankaku => "KEY_ZENKAKUHANKAKU",
        Key::Fn => "KEY_FN",
        Key::Colon => "KEY_SEMICOLON",
        Key::Quote => "KEY_APOSTROPHE",
        Key::Comma => "KEY_COMMA",
        Key::Backslash => "KEY_BACKSLASH",
        Key::Slash => "KEY_SLASH",
        Key::Pipe => "KEY_BACKSLASH",
        Key::Questionmark => "KEY_SLASH",
        Key::OpenBracket => "KEY_LEFTBRACE",
        Key::CloseBracket => "KEY_RIGHTBRACE",
        Key::Backquote => "KEY_GRAVE",
        Key::Minus => "KEY_MINUS",
        Key::Period => "KEY_DOT",
        Key::Plus => "KEY_EQUAL",
        Key::Equals => "KEY_EQUAL",
        Key::Semicolon => "KEY_SEMICOLON",
        Key::Digit0 => "KEY_0",
        Key::Digit1 => "KEY_1",
        Key::Digit2 => "KEY_2",
        Key::Digit3 => "KEY_3",
        Key::Digit4 => "KEY_4",
        Key::Digit5 => "KEY_5",
        Key::Digit6 => "KEY_6",
        Key::Digit7 => "KEY_7",
        Key::Digit8 => "KEY_8",
        Key::Digit9 => "KEY_9",
        Key::A => "KEY_A",
        Key::B => "KEY_B",
        Key::C => "KEY_C",
        Key::D => "KEY_D",
        Key::E => "KEY_E",
        Key::F => "KEY_F",
        Key::G => "KEY_G",
        Key::H => "KEY_H",
        Key::I => "KEY_I",
        Key::J => "KEY_J",
        Key::K => "KEY_K",
        Key::L => "KEY_L",
        Key::M => "KEY_M",
        Key::N => "KEY_N",
        Key::O => "KEY_O",
        Key::P => "KEY_P",
        Key::Q => "KEY_Q",
        Key::R => "KEY_R",
        Key::S => "KEY_S",
        Key::T => "KEY_T",
        Key::U => "KEY_U",
        Key::V => "KEY_V",
        Key::W => "KEY_W",
        Key::X => "KEY_X",
        Key::Y => "KEY_Y",
        Key::Z => "KEY_Z",
        Key::F1 => "KEY_F1",
        Key::F2 => "KEY_F2",
        Key::F3 => "KEY_F3",
        Key::F4 => "KEY_F4",
        Key::F5 => "KEY_F5",
        Key::F6 => "KEY_F6",
        Key::F7 => "KEY_F7",
        Key::F8 => "KEY_F8",
        Key::F9 => "KEY_F9",
        Key::F10 => "KEY_F10",
        Key::F11 => "KEY_F11",
        Key::F12 => "KEY_F12",
        Key::F13 => "KEY_F13",
        Key::F14 => "KEY_F14",
        Key::F15 => "KEY_F15",
        Key::F16 => "KEY_F16",
        Key::F17 => "KEY_F17",
        Key::F18 => "KEY_F18",
        Key::F19 => "KEY_F19",
        Key::F20 => "KEY_F20",
        Key::F21 => "KEY_F21",
        Key::F22 => "KEY_F22",
        Key::F23 => "KEY_F23",
        Key::F24 => "KEY_F24",
        Key::ChannelDown => "KEY_CHANNELDOWN",
        Key::ChannelUp => "KEY_CHANNELUP",
        Key::Close => "KEY_CLOSE",
        Key::MailForward => "KEY_FORWARDMAIL",
        Key::MailReply => "KEY_REPLY",
        Key::MailSend => "KEY_SEND",
        Key::New => "KEY_NEW",
        Key::Print => "KEY_PRINT",
        Key::Save => "KEY_SAVE",
        Key::SpellCheck => "KEY_SPELLCHECK",
        Key::SpeechInputToggle => "KEY_DICTATE",
        Key::Key11 => "KEY_NUMERIC_11",
        Key::Key12 => "KEY_NUMERIC_12",
        Key::AudioBassBoostToggle => "KEY_BASSBOOST",
        Key::LaunchApplication1 => "KEY_PROG1",
        Key::LaunchApplication2 => "KEY_PROG2",
        Key::LaunchCalendar => "KEY_CALENDAR",
        Key::LaunchContacts => "KEY_ADDRESSBOOK",
        Key::LaunchMail => "KEY_MAIL",
        Key::LaunchMusicPlayer => "KEY_AUDIO",
        Key::LaunchPhone => "KEY_PHONE",
        Key::Call => "KEY_PICKUP_PHONE",
        Key::LaunchScreenSaver => "KEY_SCREENSAVER",
        Key::Lock => "KEY_SCREENLOCK",
        Key::LaunchSpreadsheet => "KEY_SPREADSHEET",
        Key::LaunchWebBrowser => "KEY_WWW",
        Key::LaunchWebCam | Key::Camera => "KEY_CAMERA",
        Key::LaunchWordProcessor => "KEY_WORDPROCESSOR",
        Key::BrowserFavorites => "KEY_BOOKMARKS",
        Key::AppSwitch => "KEY_APPSELECT",
        Key::CameraFocus => "KEY_CAMERA_FOCUS",
        Key::EndCall => "KEY_HANGUP_PHONE",
        Key::Link => "KEY_LINK_PHONE",
        Key::MannerMode => "KEY_MODE",
        Key::Notification => "KEY_NOTIFICATION_CENTER",
        Key::VoiceDial => "KEY_VOICECOMMAND",
        Key::TV => "KEY_TV",
        Key::TV3DMode => "KEY_3D_MODE",
        Key::TVAntennaCable => "KEY_TV2",
        Key::TVAudioDescription => "KEY_AUDIO_DESC",
        Key::TVAudioDescriptionMixDown => "KEY_VOLUMEDOWN",
        Key::TVAudioDescriptionMixUp => "KEY_VOLUMEUP",
        Key::TVDataService => "KEY_DATA",
        Key::TVInput => "KEY_VIDEO",
        Key::TVInputComponent1
        | Key::TVInputComponent2
        | Key::TVInputComposite1
        | Key::TVInputComposite2
        | Key::TVInputHDMI1
        | Key::TVInputHDMI2
        | Key::TVInputHDMI3
        | Key::TVInputHDMI4 => "KEY_VIDEO",
        Key::TVInputVGA1 => "KEY_PC",
        Key::TVNumberEntry => "KEY_DIGITS",
        Key::TVRadioService => "KEY_RADIO",
        Key::TVSatellite => "KEY_SAT",
        Key::TVSatelliteBS => "KEY_SAT2",
        Key::TVSatelliteCS => "KEY_SAT2",
        Key::TVSatelliteToggle => "KEY_SAT",
        Key::TVTerrestrialAnalog | Key::TVTerrestrialDigital => "KEY_TV",
        Key::TVTimer => "KEY_TIME",
        Key::AVRInput => "KEY_AUX",
        Key::AVRPower => "KEY_POWER",
        Key::ColorF0Red => "KEY_RED",
        Key::ColorF1Green => "KEY_GREEN",
        Key::ColorF2Yellow => "KEY_YELLOW",
        Key::ColorF3Blue => "KEY_BLUE",
        Key::ClosedCaptionToggle => "KEY_SUBTITLE",
        Key::Dimmer => "KEY_BRIGHTNESS_CYCLE",
        Key::DisplaySwap => "KEY_DISPLAYTOGGLE",
        Key::DVR => "KEY_PVR",
        Key::Exit => "KEY_EXIT",
        Key::Info => "KEY_INFO",
        Key::Guide | Key::ListProgram => "KEY_EPG",
        Key::GuideNextDay => "KEY_NEXT",
        Key::GuidePreviousDay => "KEY_PREVIOUS",
        Key::InstantReplay => "KEY_RESTART",
        Key::MediaApps => "KEY_MEDIA",
        Key::MediaAudioTrack => "KEY_LANGUAGE",
        Key::MediaLast => "KEY_LAST",
        Key::NavigateIn => "KEY_SELECT",
        Key::NextFavoriteChannel => "KEY_NEXT_FAVORITE",
        Key::NavigateNext => "KEY_NEXT",
        Key::NavigateOut => "KEY_BACK",
        Key::NavigatePrevious => "KEY_PREVIOUS",
        Key::OnDemand => "KEY_VOD",
        Key::Pairing => "KEY_CONNECT",
        Key::PlaySpeedDown => "KEY_SLOW",
        Key::RcLowBattery => "KEY_BATTERY",
        Key::ScanChannelsToggle => "KEY_CHANNEL",
        Key::ScreenModeNext => "KEY_ASPECT_RATIO",
        Key::Settings => "KEY_CONFIG",
        Key::STBInput => "KEY_VIDEO",
        Key::STBPower => "KEY_POWER",
        Key::Subtitle => "KEY_SUBTITLE",
        Key::Teletext => "KEY_TEXT",
        Key::VideoModeNext => "KEY_SWITCHVIDEOMODE",
        unmapped_key => return Err(WayfireBindingError::UnmappedKey(unmapped_key)),
    };
    Ok(name)
}

#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub(super) enum WayfireBindingError {
    #[error("shortcut trigger cannot be empty")]
    Empty,
    #[error("Daiko key {0:?} has no mapped Wayfire evdev name")]
    UnmappedKey(Key),
}
